name: Deploy to BunnyCDN

on: [push]

jobs:
  bunnycdn_deploy_job:
    runs-on: ubuntu-latest
    name: Uploads files to BunnyCDN storage
    environment: BunnyCDN
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: withastro/action@v4
        with:
          package-manager: npm
      - name: Upload
        uses: skyeto/actionbunny@main
        with:
          source: "dist"
          storageZone: "${{ secrets.STORAGEZONE }}"
          storageKey: "${{ secrets.STORAGEKEY }}"
          apiKey: "${{ secrets.APIKEY }}"
