name: Deploy to BunnyCDN

on: [push]

jobs:
  bunnycdn_deploy_job:
    runs-on: ubuntu-latest
    name: Uploads files to BunnyCDN storage
    environment: BunnyCDN
    steps:
      - uses: actions/checkout@v2
      - name: Upload
        uses: skyeto/actionbunny@main
        with:
          source: ""
          storageZone: "${{ env.STORAGEZONE }}"
          storageKey: "${{ env.STORAGEKEY }}"
          apiKey: "${{ env.APIKEY }}"
